$editor = zeditor
$fileExplorer = nemo
$browser = zen-browser
$terminal = footclient

# Gaps
$windowGapsIn = 5
$windowGapsOut = 10
$singleWindowGapsOut = 25

# decoration
$blurSpecialWs = true

# borders
$windowBorderSize = 2
$activeWindowBorderColour = rgba($primaryf0) rgba($tertiaryf0) 45deg
$inactiveWindowBorderColour = rgba($onSurfaceVariant44)

# keybind overrides for caelestia
$kbToggleWindowFloating = Super+Shift, F
